; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "KSEEG_Evaluation"
#define MyAppVersion "2.4"
#define MyAppPublisher "HeWeiLun"
#define MyAppExeName "KSEEG_Evaluation.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{94B344CC-761B-4433-B33C-11EB790DD87C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=D:\CsProject\Grd3_EEGPJ\setup\KSEEG-AGREEMENT.rtf
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=D:\CsProject\Grd3_EEGPJ\setup
OutputBaseFilename=KSEEG_Evaluation_setup
SetupIconFile=D:\CsProject\Grd3_EEGPJ\setup\favicon.ico
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\CsProject\Grd3_EEGPJ\setup\Debug\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\CsProject\Grd3_EEGPJ\setup\Debug\*"; DestDir: "{app}";  Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\CsProject\Grd3_EEGPJ\setup\NDP48-x86-x64-AllOS-ENU.exe"; DestDir:"{tmp}";Flags: ignoreversion

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent



; [Code]
// function InitializeSetup(): Boolean;

  // var
    // rc:Integer;
  // begin
    // if RegKeyExists (HKLM,'SOFTWARE\Microsoft\.NETFramework\policy\v4.8') then
    // begin
      // MsgBox('已安装.NET Framework4.8,点击确定开始安装程序',mbConfirmation,MB_OK);
    // end
    
    // else
    // begin
      // MsgBox('未安装.NET Framework4.8,即将安装.NET Framework4.8',mbConfirmation,MB_OK);
      // ExtractTemporaryFile('NDP48-x86-x64-AllOS-ENU.exe');
      // Exec(ExpandConstant('{tmp}\NDP48-x86-x64-AllOS-ENU.exe'),'','',SW_SHOWNORMAL,ewWaitUntilTerminated,rc);
    // end;
    
    
    // Result := True;
  // end;
    
    
    
    
    
    
    
    
    

#define DotNetSetupFile "NDP48-x86-x64-AllOS-ENU.exe"

[Code]

const
  CDotNetSetupFile = '{#DotNetSetupFile}';
var
  VNeedRestart: Boolean;

function IsDotNetDetected(version: string; service: Cardinal): Boolean;
var
  key, versionKey: string;
  install, release, serviceCount, versionRelease: Cardinal;
  success: Boolean;
begin
  versionKey := version;
  versionRelease := 0;

  if Pos('v4.', version) = 1 then begin
    versionKey := 'v4\Full';
    case version of
      'v4.5':   versionRelease := 378389;
      'v4.5.1': versionRelease := 378675;
      'v4.5.2': versionRelease := 379893;
      'v4.6':   versionRelease := 393295;
      'v4.6.1': versionRelease := 394254;
      'v4.6.2': versionRelease := 394802;
      'v4.7':   versionRelease := 460798;
      'v4.7.1': versionRelease := 461308;
      'v4.7.2': versionRelease := 461808;
      'v4.8':   versionRelease := 528040;
      'v4.99':  versionRelease := 999999; // 奇怪版本，用于测试
    end;
  end;

  key := 'SOFTWARE\Microsoft\NET Framework Setup\NDP\' + versionKey;


  success := RegQueryDWordValue(HKLM, key, 'Install', install);


  if Pos('v4', version) = 1 then
    success := success and RegQueryDWordValue(HKLM, key, 'Servicing', serviceCount)
  else
    success := success and RegQueryDWordValue(HKLM, key, 'SP', serviceCount);


  if versionRelease > 0 then begin
    success := success and RegQueryDWordValue(HKLM, key, 'Release', release);
    success := success and (release >= versionRelease);
  end;

  Result := success and (install = 1) and (serviceCount >= service);
end;


function InitializeSetup(): Boolean;
var
  DotNetPath: string;
  ResultCode: Integer;
  CheckVersion: string;
begin
  VNeedRestart := False;


  CheckVersion := 'v4.8';

  if not IsDotNetDetected(CheckVersion, 0) then
  begin
    if MsgBox('系统缺少 .NET Framework ' + CheckVersion + '，是否立刻安装？',
              mbConfirmation, MB_YESNO) = idYes then
    begin

      ExtractTemporaryFile(CDotNetSetupFile);
      DotNetPath := ExpandConstant('{tmp}\' + CDotNetSetupFile);


      if Exec(DotNetPath, '/norestart /passive /showfinalerror', '', SW_SHOWNORMAL,
              ewWaitUntilTerminated, ResultCode) then
      begin
        if (ResultCode = 0) or (ResultCode = 1641) or (ResultCode = 3010) then
        begin

          if (ResultCode = 1641) or (ResultCode = 3010) then
            VNeedRestart := True;
          Result := True;
        end
        else
          Result := False;
      end
      else
      begin
        MsgBox('运行 .NET Framework 安装程序失败！', mbError, MB_OK);
        Result := False;
      end;
    end
    else
      Result := False;
  end
  else
  begin
    MsgBox('.NET Framework 已安装，继续安装程序', mbInformation, MB_OK);
    Result := True;
  end;
end;


function NeedRestart(): Boolean;
begin
  Result := VNeedRestart;
end;

    
 